### PR TITLE
On small screens the TA queue buttons overlap so this may be a fix

### PR DESCRIPTION
**Pull request by gabebautista11**
The TA queue buttons are hard to press and overlap so I tried to fix it by wrapping the buttons in a grid and each button has its own col. Sorry my auto format changed spaces and ' to ". All I really changed is added container class to group buttons and a col class to each button in that  (help_button, increase_button, decrease_button, dequeue button). I cannot test this because I have no clue how to get it up and running on my local machine.

### CODE REVIEW

**Comment by doublez13** [comment]
Hey thanks for the pull!
Would you mind resubmitting the request with autoformatting disabled. It's tedious to verify there aren't any unintended changes.

I have a test site that I can push the changes to and then verify it all looks good before pulling on the main site.

**Comment by gabebautista11** [comment]
yep no problem

**Comment by gabebautista11** [comment]
ok fixed it i just added cols and then a container to hold those cols.

**Comment by doublez13** [comment]
Cool thanks. I'll get this pulled into the dev site in the next day or two.

**Comment by doublez13** [comment]
Unfortunately this just squishes all the buttons together.
I've got your code pulled here: https://ta-dev.eng.utah.edu

**Pull request merged**
